[BTAT-8319] - scala and sbt update
hmrc/vat-designatory-details-frontend pull request #28
Opened 2020-09-14 15:59 UTC by sraspin

2020-09-16 12:20 UTC, sraspin commented
https://github.com/hmrc/service-manager-config/pull/2603
https://github.com/hmrc/build-jobs/pull/6540

2020-09-16 13:35 UTC, JoNB7777 requested changes

2020-09-16 13:35 UTC, JoNB7777 commented on build.sbt
> +    scalaVersion := "2.12.11",
There's a newer version available (2.12.12)

2020-09-16 13:35 UTC, JoNB7777 commented on build.sbt
>    "uk.gov.hmrc" %% "play-language" % "4.2.0-play-26",
Is there any reason for not using the playLanguageVersion variable defined above (and in particular for using an older version here)?

2020-09-16 13:35 UTC, JoNB7777 commented on project/build.properties
> +sbt.version=1.3.4
There's a newer version available (1.3.13)

2020-09-17 11:20 UTC, JoNB7777 approved these changes

2020-09-17 11:22 UTC, merged