[BTAT-8601] Updated InFlightPredicate
hmrc/vat-designatory-details-frontend pull request #48
Opened 2020-11-27 14:58 UTC by JoNB7777

2020-11-27 16:14 UTC, lewishay requested changes

2020-11-27 16:14 UTC, lewishay commented on app/models/ChangeIndicators.scala
> +                            ppob: Boolean,
Some of these field names are incorrect with respect to what they are in the JSON which is causing this model to always be read as `None`. For example, I tried user 247246260 who has `organisationDetails` pending but it let me into the service.

This service doesn't care about any other pending sections, just org details, so an easy fix to the issue would be to get rid of the other booleans here and just keep `organisationDetails`. Try hitting one of the URLs directly as user 247246260 as a way to manually test this.

2020-11-27 16:14 UTC, lewishay commented on it/connectors/VatSubscriptionConnectorISpec.scala
> +    changeIndicators = None
I would put this as `Some` and update the JSON in `VatSubscriptionStub` to include the change indicators JSON as a way to test that it's being read correctly.

2020-11-30 13:06 UTC, SheilaTran approved these changes

2020-11-30 13:06 UTC, merged